server:
  port: 3000
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: NON_EMPTY
  cloud:
    nacos:
      discovery:
        server-addr:  http://localhost:8848
  application:
    name: gulimall-member
  datasource:
    url: jdbc:mysql://47.99.155.81:3306/gulimall_ums?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志

management:
  endpoints:
    web:
      exposure:
        include: '*'